### ISSUE TITLE
Will the TS version be available in the future?

### ISSUE THREAD

**Issue by roboze** [phonycode/wenaox#2]
I want to use it in TS and get a complete prompt

**Comment by cnyballk** [comment]
under consideration, but not in the near future

**Comment by roboze** [comment]
ok, thank you, can I do this?

**Comment by cnyballk** [comment]
Of course, anyone can contribute to wenaox :+1:

**Comment by roboze** [comment]
:+1:

**Comment by roboze** [comment]
I'm sorry. I realized I couldn't do it.
