### ISSUE TITLE
options页面url参数获取的bug

### ISSUE THREAD

**Issue by leforyou** [phonycode/wenaox#7]
控制台输入能看上一个页面传的categoryId，但是 通过this.data.categoryId拿不到值
const mapState = ({ user }, options) => ({
    //userInfo: user.userInfo
    ...options, // 將query混入data 先注释  **BUG**
});
const mapMethods = ({ user }) => ({
    //getGtqUserInfo: user.getGtqUserInfo,
});

const pageConfig = {
    data: {
    },
    onLoad(options) {
        this.getListData();
    },
    getListData() {
        //获取列表数据
        let { categoryId } = this.data;
        console.log(888, this.data, this.data.categoryId); // **BUG**
        console.log(888, JSON.stringify(this.data));// **BUG**
        //空字符串查询全部
    },
};
Page(orm(mapState, mapMethods)(pageConfig));

**Comment by cnyballk** [comment]
你好，你用的是版本几？wenaox 1.1里已经不支持初始化注入获取options了，可以自己从onload中获取
